package com.ck.quiz.exam.controller;

import com.ck.quiz.exam.dto.ExamCreateDto;
import com.ck.quiz.exam.dto.ExamQueryDto;
import com.ck.quiz.exam.dto.ExamResultDto;
import com.ck.quiz.exam.dto.ExamResultHistoryItemDto;
import com.ck.quiz.exam.dto.ExamResultDetailDto;
import com.ck.quiz.exam.dto.ExamSubmitDto;
import com.ck.quiz.exam.dto.ExamUpdateDto;
import com.ck.quiz.exam.entity.Exam;
import com.ck.quiz.exam.service.ExamService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;

@Tag(name = "试卷管理", description = "试卷相关的API接口")
@RestController
@RequestMapping("/api/exam")
public class ExamController {

    @Autowired
    private ExamService examService;

    @Operation(summary = "创建试卷", description = "创建新的试卷")
    @PostMapping("/create")
    public ResponseEntity createExam(
            @Parameter(description = "试卷创建信息", required = true) @Valid @RequestBody ExamCreateDto examCreateDto) {
        return ResponseEntity.ok(examService.createExam(examCreateDto));
    }

    @Operation(summary = "更新试卷", description = "更新指定试卷的信息")
    @PutMapping("/update")
    public ResponseEntity updateExam(
            @Parameter(description = "试卷更新信息", required = true) @Valid @RequestBody ExamUpdateDto examUpdateDto) {
        return ResponseEntity.ok(examService.updateExam(examUpdateDto));
    }

    @Operation(summary = "删除试卷", description = "根据ID删除指定试卷")
    @DeleteMapping("/{id}")
    public ResponseEntity deleteExam(
            @Parameter(description = "试卷ID", required = true) @PathVariable String id) {
        return ResponseEntity.ok(examService.deleteExam(id));
    }

    @Operation(summary = "获取试卷详情", description = "根据ID获取试卷详细信息")
    @GetMapping("/{id}")
    public ResponseEntity getExamById(
            @Parameter(description = "试卷ID", required = true) @PathVariable String id) {
        return ResponseEntity.ok(examService.getExamById(id));
    }

    @Operation(summary = "分页查询试卷", description = "根据条件分页查询试卷列表")
    @GetMapping
    public ResponseEntity searchExams(
            @Parameter(description = "试卷名称") @RequestParam(required = false) String keyWord,
            @Parameter(description = "试卷状态") @RequestParam(required = false) Exam.ExamPaperStatus status,
            @Parameter(description = "页码") @RequestParam(defaultValue = "0") int pageNum,
            @Parameter(description = "每页大小") @RequestParam(defaultValue = "20") int pageSize,
            @Parameter(description = "排序字段") @RequestParam(defaultValue = "create_date") String sortColumn,
            @Parameter(description = "排序方向") @RequestParam(defaultValue = "desc") String sortType) {
        
        ExamQueryDto queryDto = new ExamQueryDto();
        queryDto.setKeyWord(keyWord);
        queryDto.setStatus(status);
        queryDto.setPageNum(pageNum);
        queryDto.setPageSize(pageSize);
        queryDto.setSortColumn(sortColumn);
        queryDto.setSortType(sortType);
        
        return ResponseEntity.ok(examService.searchExams(queryDto));
    }

    // 新增：一键智能生成试卷
    @Operation(summary = "一键智能生成试卷", description = "根据题目数量、总分、学科与类目自动选题并可选择立即发布")
    @PostMapping("/auto-generate")
    public ResponseEntity autoGenerateExam(
            @Parameter(description = "生成配置", required = true) @Valid @RequestBody com.ck.quiz.exam.dto.ExamAutoGenerateDto autoGenerateDto) {
        return ResponseEntity.ok(examService.autoGenerateExam(autoGenerateDto));
    }

    @Operation(summary = "发布试卷", description = "将试卷状态更改为已发布")
    @PostMapping("/{id}/publish")
    public ResponseEntity publishExam(
            @Parameter(description = "试卷ID", required = true) @PathVariable String id) {
        return ResponseEntity.ok(examService.publishExam(id));
    }

    @Operation(summary = "归档试卷", description = "将试卷状态更改为已归档")
    @PostMapping("/{id}/archive")
    public ResponseEntity archiveExam(
            @Parameter(description = "试卷ID", required = true) @PathVariable String id) {
        return ResponseEntity.ok(examService.archiveExam(id));
    }

    @Operation(summary = "添加题目到试卷", description = "为试卷添加新的题目")
    @PostMapping("/{id}/questions")
    public ResponseEntity addQuestionToExam(
            @Parameter(description = "试卷ID", required = true) @PathVariable String id,
            @Parameter(description = "题目ID", required = true) @RequestParam String questionId,
            @Parameter(description = "题目顺序", required = true) @RequestParam Integer orderNo,
            @Parameter(description = "分值", required = true) @RequestParam Integer score) {
        examService.addQuestionToExam(id, questionId, orderNo, score);
        return ResponseEntity.ok().build();
    }

    @Operation(summary = "批量添加题目到试卷", description = "为试卷批量添加多个题目")
    @PostMapping("/{id}/questions/batch")
    public ResponseEntity addQuestionsToExam(
            @Parameter(description = "试卷ID", required = true) @PathVariable String id,
            @Parameter(description = "题目ID列表", required = true)
            @RequestBody List<String> questionIds) {
        examService.addQuestionsToExam(id, questionIds);
        return ResponseEntity.ok().build();
    }


    @Operation(summary = "从试卷中移除题目", description = "从试卷中移除指定题目")
    @DeleteMapping("/{id}/questions/{questionId}")
    public ResponseEntity removeQuestionFromExam(
            @Parameter(description = "试卷ID", required = true) @PathVariable String id,
            @Parameter(description = "题目ID", required = true) @PathVariable String questionId) {
        examService.removeQuestionFromExam(id, questionId);
        return ResponseEntity.ok().build();
    }

    @Operation(summary = "更新试卷中的题目", description = "更新试卷中题目的顺序和分值")
    @PutMapping("/{id}/questions/{questionId}")
    public ResponseEntity updateExamQuestion(
            @Parameter(description = "试卷ID", required = true) @PathVariable String id,
            @Parameter(description = "题目ID", required = true) @PathVariable String questionId,
            @Parameter(description = "题目顺序") @RequestParam(required = false) Integer orderNo,
            @Parameter(description = "分值") @RequestParam(required = false) Integer score) {
        examService.updateExamQuestion(id, questionId, orderNo, score);
        return ResponseEntity.ok().build();
    }

    @Operation(summary = "提交考试", description = "提交答案并返回评分结果")
    @PostMapping("/{id}/submit")
    public ResponseEntity<ExamResultDto> submitExam(
            @Parameter(description = "试卷ID", required = true) @PathVariable String id,
            @Parameter(description = "提交内容", required = true) @RequestBody ExamSubmitDto submitDto) {
        return ResponseEntity.ok(examService.submitExam(id, submitDto));
    }

    @Operation(summary = "查询用户历史答卷", description = "根据用户ID（可选试卷ID）查询历史答卷列表")
    @GetMapping("/results")
    public ResponseEntity<List<ExamResultHistoryItemDto>> listUserResults(
            @Parameter(description = "用户ID", required = true) @RequestParam String userId,
            @Parameter(description = "试卷ID", required = false) @RequestParam(required = false) String examId) {
        return ResponseEntity.ok(examService.listUserResults(userId, examId));
    }

    @Operation(summary = "获取答卷详情", description = "根据结果ID获取完整答卷详情")
    @GetMapping("/results/{resultId}")
    public ResponseEntity<ExamResultDetailDto> getExamResultDetail(
            @Parameter(description = "答卷结果ID", required = true) @PathVariable String resultId) {
        return ResponseEntity.ok(examService.getExamResultById(resultId));
    }
}