package com.ck.quiz.exam.dto;

import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Positive;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * 一键智能生成试卷的请求DTO
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class ExamAutoGenerateDto {

    /**
     * 题目数量
     */
    @NotNull(message = "题目数量不能为空")
    @Positive(message = "题目数量必须为正数")
    private Integer questionCount;

    /**
     * 总分
     */
    @NotNull(message = "总分不能为空")
    @Positive(message = "总分必须为正数")
    private Integer totalScore;

    /**
     * 学科ID
     */
    @NotNull(message = "学科不能为空")
    private String subjectId;

    /**
     * 是否立即发布（默认true）
     */
    private Boolean publishImmediately = true;

    /**
     * 考试时长（分钟，可选）
     */
    @Positive(message = "考试时长必须为正数")
    private Integer durationMinutes;

    /**
     * 试卷名称（可选，不传则自动生成）
     */
    private String name;

    /**
     * 试卷描述（可选）
     */
    private String description;
}